# Generated by Django 4.1.5 on 2023-02-24 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0002_customerpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
